/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Dell
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        mbLista = new javax.swing.JMenuBar();
        jmMenu = new javax.swing.JMenu();
        jmiCerrarSesion = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmVentas = new javax.swing.JMenu();
        jmiGenerarVentas = new javax.swing.JMenuItem();
        jmMantenimiento = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiProducto = new javax.swing.JMenuItem();
        jmiVendedor = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmiReporteVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        jmMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jmMenu.setText("MENÚ");

        jmiCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiCerrarSesion.setText("Cerrar Sesión");
        jmMenu.add(jmiCerrarSesion);

        jmiSalir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiSalir.setText("Salir");
        jmMenu.add(jmiSalir);

        mbLista.add(jmMenu);

        jmVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas.png"))); // NOI18N
        jmVentas.setText("VENTAS");

        jmiGenerarVentas.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiGenerarVentas.setText("Generar Venta");
        jmVentas.add(jmiGenerarVentas);

        mbLista.add(jmVentas);

        jmMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento.png"))); // NOI18N
        jmMantenimiento.setText("MANTENIMIENTO");

        jmiCliente.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiCliente.setText("Cliente");
        jmMantenimiento.add(jmiCliente);

        jmiProducto.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiProducto.setText("Producto");
        jmMantenimiento.add(jmiProducto);

        jmiVendedor.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiVendedor.setText("Vendedor");
        jmMantenimiento.add(jmiVendedor);

        mbLista.add(jmMantenimiento);

        jmReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        jmReportes.setText("REPORTES");

        jmiReporteVenta.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmiReporteVenta.setText("Reporte de Venta");
        jmReportes.add(jmiReporteVenta);

        mbLista.add(jmReportes);

        setJMenuBar(mbLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jdpPrincipal;
    public javax.swing.JMenu jmMantenimiento;
    public javax.swing.JMenu jmMenu;
    public javax.swing.JMenu jmReportes;
    public javax.swing.JMenu jmVentas;
    public javax.swing.JMenuItem jmiCerrarSesion;
    public javax.swing.JMenuItem jmiCliente;
    public javax.swing.JMenuItem jmiGenerarVentas;
    public javax.swing.JMenuItem jmiProducto;
    public javax.swing.JMenuItem jmiReporteVenta;
    public javax.swing.JMenuItem jmiSalir;
    public javax.swing.JMenuItem jmiVendedor;
    public javax.swing.JMenuBar mbLista;
    // End of variables declaration//GEN-END:variables
}
